package x

func _t() {
	/* Code generated by some program. DO NOT EDIT. */
	// /*-style comments don't count, so should report.
	var d Direction
	switch d { // want "missing cases in switch of type Direction: E, S, W, directionInvalid"
	case N:
	}
}
