// Attached to package.
//
// Hello, world.
// Code generated by "some program"; DO NOT EDIT.
// More text.
package generated

func _doc_0() {
	var d Direction
	switch d {
	case N:
	}

	_ = map[Direction]int{
		N: 1,
	}
}
