/* Code generated by "some program"; DO NOT EDIT. */
package generated

func _doc_2() {
	var d Direction
	switch d { // want "^missing cases in switch of type Direction: E, S, W, directionInvalid$"
	case N:
	}

	_ = map[Direction]int{ // want "^missing map keys of type Direction: E, S, W, directionInvalid$"
		N: 1,
	}
}

// Explanation: /*-style comments don't count.
