// Attached to package.
//
// Hello, world.
// Code generated by "some program"; DO NOT EDIT.
// More text.
package generated

func _doc_0() {
	var d Direction
	switch d { // want "^missing cases in switch of type Direction: E, S, W, directionInvalid$"
	case N:
	}
}
