// Code generated by "some program"; DO NOT EDIT.
// more text
//

package generated

func _3() {
	var d Direction
	switch d { // want "^missing cases in switch of type Direction: E, S, W, directionInvalid$"
	case N:
	}
}
