// Code generated by "some program"; DO NOT EDIT.

package generated

func _0() {
	var d Direction
	switch d { // want "^missing cases in switch of type Direction: E, S, W, directionInvalid$"
	case N:
	}

	_ = map[Direction]int{ // want "^missing keys in map of key type Direction: E, S, W, directionInvalid$"
		N: 1,
	}
}
