// Attached to package.
//
// Hello, world.
// Code generated by "some program"; DO NOT EDIT.
// More text.
package generated

func _doc_0() {
	var d Direction
	switch d { // want "^missing cases in switch of type generated.Direction: generated.E, generated.S, generated.W, generated.directionInvalid$"
	case N:
	}

	_ = map[Direction]int{ // want "^missing keys in map of key type generated.Direction: generated.E, generated.S, generated.W, generated.directionInvalid$"
		N: 1,
	}
}
