// Code generated by "some program"; DO NOT EDIT.
// more text
//

package generated

func _3() {
	var d Direction
	switch d { // want "^missing cases in switch of type Direction: E, S, W, directionInvalid$"
	case N:
	}

	_ = map[Direction]int{ // want "^missing map keys of type Direction: E, S, W, directionInvalid$"
		N: 1,
	}
}
