// Code generated by xxx. DO NOT EDIT.

package typ

type (
	t4 int // want t4:"^permittedtype$" t4:"^enumerated$" t4:"^elements:k0 = 0$"
)

const (
	k0 t4 = iota // want k0:"^enumerated$" k0:"^elementof:t4$"
)
