package exp

// NOTE: Feel free to delete code below. This is a temporary scratchpad for use
// when working on bugfixes or new code for exhaustive.

type Direction int

var (
	N                Direction = 1
	E                Direction = 2
	S                Direction = 3
	W                Direction = 4
	directionInvalid Direction = 5
)

func _s() {
	// Code generated by some program. DO NOT EDIT.
	// generated file as marked by comment above, so should not report.
	var d Direction
	switch d {
	case N:
	}
}
