on: [push, pull_request]
name: build, test, and vet
jobs:
  main:
    strategy:
      matrix:
        go-version: [1.14, 1.16, 1.18, 1.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: install go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: checkout code
      uses: actions/checkout@v2

    - name: build
      run: make build

    - name: install vet tools
      if: ${{ matrix.go-version < '1.16' }}
      run: |
        go get github.com/nishanths/exhaustive/cmd/exhaustive
        go get github.com/gordonklaus/ineffassign
        go get github.com/kisielk/errcheck
        go get honnef.co/go/tools/cmd/staticcheck
      if: ${{ matrix.go-version >= '1.16' }}
      run: |
        go install github.com/nishanths/exhaustive/cmd/exhaustive@latest
        go install github.com/gordonklaus/ineffassign@latest
        go install github.com/kisielk/errcheck@latest
        go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: vet
      run: make vet

    - name: test
      run: make test
